language: node_js
sudo: false
dist: trusty
node_js:
  - 8.9.1

branches:
  only:
    - master

addons:
  firefox: latest
  chrome: stable

before_script:
  - npm install
  - npm install -g @angular/cli
  - npm install -g karma
  - ng build

#script: karma start config/karma.conf.js --single-run


